use `library`;
DELIMITER //
CREATE DEFINER = CURRENT_USER TRIGGER `library`.`users_AFTER_INSERT` AFTER INSERT ON `users` FOR EACH ROW
BEGIN
END
DELIMITER //


DELIMITER //
CREATE DEFINER = CURRENT_USER TRIGGER `library`.`users_AFTER_DELETE` AFTER DELETE ON `users` FOR EACH ROW
BEGIN
END
DELIMITER //

DELIMITER //
CREATE DEFINER = CURRENT_USER TRIGGER `library`.`rented_BEFORE_INSERT` BEFORE INSERT ON `rented` FOR EACH ROW
BEGIN
END
DELIMITER //

DELIMITER //
CREATE DEFINER = CURRENT_USER TRIGGER `library`.`rented_AFTER_INSERT` AFTER INSERT ON `rented` FOR EACH ROW
BEGIN
END
DELIMITER //